### ISSUE TITLE
Todo When We Get Hands On Robot

### ISSUE THREAD

**Issue by MrTinker64** [SFUnity/AKit-Phoenix-Offseason-2024#3]
- [ ] Get the motor current limits so we can hardcode them
- [ ] Logging to a USB stick
  - [ ] Logging with PowerDistribution and URCL
- [ ] new code
  - [ ] Check if joystick axes are correct
  - [ ] ModuleIOMixed + swerve stuff
    - [ ] See if the drift still exists
  - [ ] intake code
  - [ ] shooter code 
    - [ ] pivot
    - [ ] flywheels
    - [ ] feeder
    - [ ] distance sensor
  - [ ] LED code
  - [ ] vision code
  - [ ] Shuffleboard button replays correctly
  - [ ] limelight port forwarding
  - [ ] the various drive modes
    - [ ] pov
    - [ ] heading control
    - [ ] full auto drive
    - [ ] slow mode
  - [ ] vision stdDevs
  - [ ] auto coasting
  - [ ] vision filters
  - [ ] alliance flipping and all sorts of pose related functions to make sure coordinate system isn't causing issues
  - [ ] Auto aim
  - [ ] Tune dynamic cropping, specifically the crop buffer and default crop size
  - [ ] Choreo autos
